=== gina-alaska/arctic-pastfinder-schemas/page-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Logbook page schema for the Arctic Pastfinder project",
  "type": "object",
  "required": [
    "title",
    "content",
    "logged_at",
    "category",
    "index",
    "url"
  ],
  "properties": {
    "title": {
      "type": "string"
    },
    "content": {
      "type": "string"
    },
    "logged_at": {
      "type": "string",
      "description": "Date of the logbook page",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    },
    "category": {
      "type": "string"
    },
    "index": {
      "type": "integer"
    },
    "logbook": {
      "type": "object",
      "description": "subset of the logbook schema",
      "required": [
        "url"
      ],
      "properties": {
        "url": {
          "type": "string",
          "description": "URI Identifier url for resource instance"
        }
      }
    },
    "locations": {
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "required": [
          "type",
          "coordinates"
        ],
        "properties": {
          "type": {
            "type": "string"
          },
          "coordinates": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "type": "number"
            }
          }
        }
      }
    },
    "links": {
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "required": [
          "name",
          "url"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        }
      }
    },
    "url": {
      "type": "string",
      "description": "URI Identifier url for resource instance"
    }
  }
}

=== gina-alaska/arctic-pastfinder-schemas/page.json
{
  "title": "25 June 1879",
  "content": " <br />Lat 38.1, Long -122.3 <br />Navy Yard Mare Island, Cal. <br /> <br />Coal consumed during the preceding 24 hours: 1 tons 1360 lbs <br />Coal remaining on hand at noon: 140 tons 1340 lbs <br /> <br />At 2pm the ship was placed in commission by Captain P.C. Johnson, US Navy, and turned over to the command of Lieutenant George W. DeLong, US Navy. <br /> <br />Officers <br />Lieutenant George W. DeLong, U.S. Navy <br />Lieutenant Chas. W. Chipp, U.S. Navy <br />Master John W. Danenhower, U.S. Navy <br />P.A. Eng. George W. Melville, U.S. Navy <br />P.A. Surg. G.M. Ambler, U.S. Navy <br /> <br />Crew <br />Walter Lee, Coppersmith <br />Jas. H. Bartlett, Fireman <br />William Dunbar, Seaman <br />Louis P. Noros, Seaman <br />H.W. Leach, Seaman <br />Henry Wilson, Seaman <br />C.A. Gortz, Seaman <br />R.E. Johnson, Seaman <br />Edward Starr, Seaman <br />Henry D. Warren, Seaman <br />H.R. Kaack, Seaman <br />A.G. Kuehne, Seaman <br />F.E. Mansen, Seaman <br />H.H. Erickson, Seaman <br />W.F.C. Nindemann, Seaman <br />Adolph Dressler, Seaman <br />John Lauterbach, Coal Heaver <br />Geo. W. Boyd, Coal Heaver <br />Nelse Iversen, Coal Heaver <br /> <br />At 2.10 slipped from buoy and stood down the river with a pilot and having on board a board of officers consisting of Capt. P.C. Johnson, USN, Cmdr. C.J. McDougal, USN and Chief Engineers George F. Kurtz and Edward Farmer US Navy. Engines working smoothly and well. Ship's draught forward 10' 11\" Aft 13' 3 ½\". At 3.07 crossed range of Thompson's Point and Pyramid Rock and set course by landmark on Jamalpais. Put three patent logs over. Strong flood tide and gentle breeze from S. <br />[signed] Chas. W. Chipp, Lieutenant U.S.N. Executive Officer <br /> <br />4 to 6pm <br />Clear and pleasant. Gentle wind from S.S.W. At 4.07 patent logs showed 4.6, 4.3, 4.4. Mean speed per hour 4.4 knots. The turning power of the ship was then tested. Complete circle with helm a ‘port was made in 7m 41s. Complete circle with helm a ‘starb‘d was made in 5m 38s. Estimated diameter of circles 110 yards At 4.45 started on return over previous track and crossed range at 5.10. Distance per patent logs 2 ¼ miles. Speed per hour 5.4 knots. Mean speed for both runs 4.9 knots. Returned to Navy Yard 5.30 and moored to lower buoy off Sectional Dock. Board of officers left the ship at 5.30. Hauled fires. Draught 10' 11\" forward 13' 3½\" aft. <br />[signed] John Cole <br /> <br />6 to 8pm <br />Clear and pleasant. Light breeze from S. Ship swung to ebb tide at 6.30. <br />[signed] William Nindemann <br /> <br />8pm to midnight <br />Clear and pleasant. Light S.W. wind increasing to a strong breeze at 10. <br />[signed] Alfred Sweetman <br /> <br />Moon 1° S. <br />First quarter <br /> <br />50a27fd77438ae05bd000029: (http://oldweather.s3.amazonaws.com/ow3/final/USS Jeannette/vol001of004/vol001_010_0.jpg) <br /> ",
  "logged_at": "1879-06-25",
  "category": "log_page",
  "index": 5,
  "logbook": {
    "title": "June 1879 to May 1880, Arctic Exploring Expedition",
    "description": null,
    "starts_at": "1879-06-25",
    "ends_at": "1880-05-30",
    "page_count": 375,
    "url": "http://shiplog-website.127.0.0.1.xip.io/ships/uss-jeannette/logbooks/june-1879-to-may-1880-arctic-exploring-expedition"
  },
  "locations": [
    {
      "type": "Point",
      "coordinates": [
        -122.3,
        38.1
      ]
    }
  ],
  "links": [
    {
      "name": "50a27fd77438ae05bd000029",
      "url": "http://oldweather.s3.amazonaws.com/ow3/final/USS Jeannette/vol001of004/vol001_010_0.jpg"
    }
  ],
  "url": "http://shiplog-website.127.0.0.1.xip.io/ships/uss-jeannette/logbooks/june-1879-to-may-1880-arctic-exploring-expedition/pages/6"
}
