=== gina-alaska/arctic-pastfinder-schemas/logbook/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Logbook schema for the Arctic Pastfinder project.",
  "type": "object",
  "required": [
    "title",
    "starts_at",
    "ends_at",
    "url"
  ],
  "properties": {
    "title": {
      "type": "string",
      "description": "Logbook title"
    },
    "description": {
      "type": "string",
      "description": "Logbook description"
    },
    "starts_at": {
      "type": "date",
      "description": "Starting date of the logbook, usually the date of the first page in the logbook",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    },
    "ends_at": {
      "type": "date",
      "description": "Ending date of the logbook, usually the date of the last page in the logbook",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
    },
    "page_count": {
      "type": "integer"
    },
    "url": {
      "type": "string",
      "description": "URI Identifier url for resource instance"
    }
  }
}

=== gina-alaska/arctic-pastfinder-schemas/logbook/example.json
{
  "title": "June 1879 to May 1880, Arctic Exploring Expedition",
  "description": "Description of the logbook",
  "starts_at": "1879-06-25",
  "ends_at": "1880-05-30",
  "page_count": 375,
  "url": "http://shiplog-website.127.0.0.1.xip.io/ships/uss-jeannette/logbooks/june-1879-to-may-1880-arctic-exploring-expedition"
}
